jobs:
  publish:
    runs-on: ubuntu-latest
    needs:
      - tag
    environment:
      name: pypi
    permissions:
      id-token: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v6
      - name: Install 'uv'
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          version: latest
      - name: Build Python package
        run: uv build
      - name: Upload distribution
        run: uv publish --trusted-publishing always
